services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "7u"                # Phiên bản Windows 7
      USERNAME: "Administrator"    # Tên tài khoản là Administrator
      PASSWORD: "negancsl123@@"    # Mật khẩu là negancsl123@@
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp    # Cổng RDP
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    restart: always             # Tự động khởi động lại container khi bị lỗi
    stop_grace_period: 2m       # Thời gian đợi trước khi dừng container khi có lệnh dừng
