services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "7u"
      USERNAME: "Administrator"
      PASSWORD: "negancsl123@@"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      DISK_SIZE: "100"
      DISK1_SIZE: "100"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    restart: always
    stop_grace_period: 2m

environment:
  USERNAME: "bill"
  PASSWORD: "gates"
