services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "7u"
      USERNAME: "Neganconsole"
      PASSWORD: "negancsl123@@"
      RAM_SIZE: "16G"
      CPU_CORES: "4"
      DISK_SIZE: "20G"
      DISK2_SIZE: "10G"
    devices: []
    cap_add:
      - NET_ADMIN
    ports:
      - "8006:8006"
      - "3389:3389/tcp"
      - "3389:3389/udp"
    stop_grace_period: 2m
